name: marvel
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get:
  http:
  dio:
  crypto:
  flutter_cache_manager:
  path_provider:
  shared_preferences:
  google_fonts:
  font_awesome_flutter:
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1
  webview_flutter: ^4.2.0
  cupertino_icons: ^1.0.2

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/marvelSplash.jpeg"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/marvelSplash.jpeg"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/marvelSplash.jpeg"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/marvelLogo.png
    - assets/marvelSplash.jpeg
    - assets/marvel.png
